// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'dailyWeatherData.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

DailyWeatherData _$DailyWeatherDataFromJson(Map<String, dynamic> json) {
  return DailyWeatherData(
    json['time'] as int,
    json['summary'] as String,
    json['icon'] as String,
    json['sunriseTime'] as int,
    json['sunsetTime'] as int,
    (json['moonPhase'] as num)?.toDouble(),
    (json['precipIntensity'] as num)?.toDouble(),
    (json['precipIntensityMax'] as num)?.toDouble(),
    json['precipIntensityMaxTime'] as int,
    (json['precipProbability'] as num)?.toDouble(),
    json['precipType'] as String,
    (json['temperatureHigh'] as num)?.toDouble(),
    json['temperatureHighTime'] as int,
    (json['temperatureLow'] as num)?.toDouble(),
    json['temperatureLowTime'] as int,
    (json['apparentTemperatureHigh'] as num)?.toDouble(),
    json['apparentTemperatureHighTime'] as int,
    (json['apparentTemperatureLow'] as num)?.toDouble(),
    json['apparentTemperatureLowTime'] as int,
    (json['dewPoint'] as num)?.toDouble(),
    (json['humidity'] as num)?.toDouble(),
    (json['pressure'] as num)?.toDouble(),
    (json['windSpeed'] as num)?.toDouble(),
    (json['windGust'] as num)?.toDouble(),
    json['windGustTime'] as int,
    json['windBearing'] as int,
    (json['cloudCover'] as num)?.toDouble(),
    json['uvIndex'] as int,
    json['uvIndexTime'] as int,
    (json['visibility'] as num)?.toDouble(),
    (json['ozone'] as num)?.toDouble(),
    (json['temperatureMin'] as num)?.toDouble(),
    json['temperatureMinTime'] as int,
    (json['temperatureMax'] as num)?.toDouble(),
    json['temperatureMaxTime'] as int,
    (json['apparentTemperatureMin'] as num)?.toDouble(),
    json['apparentTemperatureMinTime'] as int,
    (json['apparentTemperatureMax'] as num)?.toDouble(),
    json['apparentTemperatureMaxTime'] as int,
  );
}

Map<String, dynamic> _$DailyWeatherDataToJson(DailyWeatherData instance) =>
    <String, dynamic>{
      'time': instance.time,
      'summary': instance.summary,
      'icon': instance.icon,
      'sunriseTime': instance.sunriseTime,
      'sunsetTime': instance.sunsetTime,
      'moonPhase': instance.moonPhase,
      'precipIntensity': instance.precipIntensity,
      'precipIntensityMax': instance.precipIntensityMax,
      'precipIntensityMaxTime': instance.precipIntensityMaxTime,
      'precipProbability': instance.precipProbability,
      'precipType': instance.precipType,
      'temperatureHigh': instance.temperatureHigh,
      'temperatureHighTime': instance.temperatureHighTime,
      'temperatureLow': instance.temperatureLow,
      'temperatureLowTime': instance.temperatureLowTime,
      'apparentTemperatureHigh': instance.apparentTemperatureHigh,
      'apparentTemperatureHighTime': instance.apparentTemperatureHighTime,
      'apparentTemperatureLow': instance.apparentTemperatureLow,
      'apparentTemperatureLowTime': instance.apparentTemperatureLowTime,
      'dewPoint': instance.dewPoint,
      'humidity': instance.humidity,
      'pressure': instance.pressure,
      'windSpeed': instance.windSpeed,
      'windGust': instance.windGust,
      'windGustTime': instance.windGustTime,
      'windBearing': instance.windBearing,
      'cloudCover': instance.cloudCover,
      'uvIndex': instance.uvIndex,
      'uvIndexTime': instance.uvIndexTime,
      'visibility': instance.visibility,
      'ozone': instance.ozone,
      'temperatureMin': instance.temperatureMin,
      'temperatureMinTime': instance.temperatureMinTime,
      'temperatureMax': instance.temperatureMax,
      'temperatureMaxTime': instance.temperatureMaxTime,
      'apparentTemperatureMin': instance.apparentTemperatureMin,
      'apparentTemperatureMinTime': instance.apparentTemperatureMinTime,
      'apparentTemperatureMax': instance.apparentTemperatureMax,
      'apparentTemperatureMaxTime': instance.apparentTemperatureMaxTime,
    };
